#!/bin/bash
     
# Invoke the Forever module (to STOP our Node.js server).
./node_modules/forever/bin/forever stop server.js


./node_modules/forever/bin/forever \
	start \
	-al forever.log \
	-ao out.log \
	-ae err.log \
	server.js
